# Generated by Django 2.2.4 on 2019-08-09 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='subtitle',
            field=models.CharField(default='SOME STRING', max_length=140),
        ),
    ]
