# Generated by Django 2.2.4 on 2019-08-09 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail_img',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnail_post'),
        ),
    ]
